-- Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

-- 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

-- By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

-- Running time: 0.00 secs

module P2 where

fibs :: [Integer]
fibs = 1 : scanl (+) 1 fibs

evenAndLessFibs :: [Integer]
evenAndLessFibs = filter even (takeWhile (< 4000000) fibs)


m = sum evenAndLessFibs
