-- Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

-- 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

-- It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

-- Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

-- Running time: 2.00 secs

import P45 (pentagonals)
import qualified Data.Set as Set

ps :: Set.Set Integer
ps = Set.fromList (take 10000 pentagonals)

sAndDPentagonal :: Integer -> Integer -> Bool
sAndDPentagonal x y = isPentagonal (x+y) && isPentagonal (x-y)
  where isPentagonal a = Set.member a ps

m = head [p - l | p <- pentagonals, l <- takeWhile (< p) pentagonals, sAndDPentagonal p l]
